import os
import sys

sys.path.insert(1, os.path.join(sys.path[0], ".."))

from dotenv import load_dotenv
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langgraph.analyze_data import data_analyzer
from langgraph.checkpoint.memory import MemorySaver
from langgraph.generate_sql_query import generate_and_run_sql_query
from langgraph.graph import END, START, MessagesState, StateGraph
from langgraph.prebuilt import ToolNode
from prompt_templates.router_template import SYSTEM_PROMPT

load_dotenv()

tools = [generate_and_run_sql_query, data_analyzer]
model = ChatOpenAI(model="gpt-4", temperature=0).bind_tools(tools)


# if the last message has a tool call, then we continue to the tools node
# otherwise, we stop
def should_continue(state: MessagesState):
    """
    Determines the next step based on the state of messages.

    Args:
        state (MessagesState): The current state containing messages.

    Returns:
        str: "tools" if the last message contains tool calls, otherwise END.
    """
    messages = state["messages"]
    last_message = messages[-1]
    if last_message.tool_calls:
        return "tools"
    return END


def call_model(state: MessagesState):
    """
    Calls the model with the provided state and returns the response.

    Args:
        state (MessagesState): The state containing the messages to be sent to the model.

    Returns:
        dict: A dictionary containing the model's response messages.
    """
    messages = state["messages"]
    response = model.invoke(messages)
    return {"messages": [response]}


def create_agent_graph():
    """
    Creates and compiles an agent workflow graph.

    The function sets up a state graph with nodes and edges representing 
    the workflow of an agent. It includes the following steps:
    - Initializes a StateGraph with MessagesState.
    - Adds a tool node and an agent node to the graph.
    - Defines the edges between the nodes, including conditional edges.
    - Sets up a checkpointer using MemorySaver.
    - Compiles the workflow into an application.

    Returns:
        app: The compiled workflow application.
    """
    workflow = StateGraph(MessagesState)

    tool_node = ToolNode(tools)
    workflow.add_node("agent", call_model)
    workflow.add_node("tools", tool_node)

    workflow.add_edge(START, "agent")
    workflow.add_conditional_edges(
        "agent",
        should_continue,
    )
    workflow.add_edge("tools", "agent")

    checkpointer = MemorySaver()
    app = workflow.compile(checkpointer=checkpointer)
    return app


def run_agent(query):
    """
    Executes an agent with the provided query and returns the final response.

    Args:
        query (str): The input query to be processed by the agent.

    Returns:
        str: The content of the final message generated by the agent.

    Notes:
        - The function creates an agent graph using `create_agent_graph()`.
        - It invokes the agent with a list of messages, including a `HumanMessage` with the query content and a `SystemMessage` with a predefined system prompt.
        - The configuration includes a thread ID set to 42.
    """
    app = create_agent_graph()

    final_state = app.invoke(
        {"messages": [HumanMessage(content=query), SystemMessage(content=SYSTEM_PROMPT)]},
        config={"configurable": {"thread_id": 42}},
    )
    return final_state["messages"][-1].content
